### ISSUE TITLE
Firecross下载图片右边和底部缺失

### ISSUE THREAD

**Issue by lasthm** [Timesient/manga-download-scripts#2]
使用Read me.md描述中的AllInOneDownloader对应Greasy Fork链接安装的最新版本，下载Firecross.jp上的漫画得到的图片会在右边和底部有一段透明缺失。
示例漫画链接：https://firecross.jp/reader/6426?trial=0&token=3b63e4b0-06fd-4d6c-bb48-9147c2c22c3c&vertical=0
网站上显示内容：https://tupian.li/images/2022/10/18/2022-10-18-15-30-9.png
下载的图片：https://tupian.li/images/2022/10/18/01.png

**Comment by Timesient** [comment]
感谢反馈，问题已修复，请查验

**Comment by lasthm** [comment]
感谢修复
