### ISSUE TITLE
Request to add new site：一迅プラス

### ISSUE THREAD

**Issue by lasthm** [Timesient/manga-download-scripts#4]
请求增加一迅プラス的支持：https://ichijin-plus.com/

用的是和コロナEX同款的阅读器，之前能用和コロナEX相同的下载方案下载，前段时间一迅プラス好像进行了某些修改之后，就无法下载了。
之前用的下载方案是ccdl，现在ccdl还能正常下载コロナEX，一迅プラス失效，看ccdl的报错好像是一迅プラス的漫画页json无法获取。那边提了issue，但那边好久不维护了。

**Comment by Timesient** [comment]
已添加，请查验

**Comment by lasthm** [comment]
正常运行，非常感谢
