### ISSUE TITLE
Request: renta.papy.co.jp & ebookrenta.com

### ISSUE THREAD

**Issue by Fallen98** [Timesient/manga-download-scripts#6]
Would you be able to add:

https://renta.papy.co.jp/ 
&
https://www.ebookrenta.com/

While the sites look different they seem to be using the same reader.

**Comment by Timesient** [comment]
`RentaDownloader` and `EbookrentaDownloader` has been added. 

They works well in `Sample` or `Take a peek!` books, but not tested in `paid-to-fully-read` books yet.

**Comment by Timesient** [comment]
In addition, `RentaDownloader` is not work for **ノベル(novel)** and **実用書(functional book)**, those pages are too complicated to download.

**Comment by Fallen98** [comment]
> `RentaDownloader` and `EbookrentaDownloader` has been added.
> 
> They work well in `Sample` or `Take a peek!` books, but not tested in `paid-to-fully-read` books yet.

It's working fine on paid books, thank you
